### ISSUE TITLE
grunt-strip-code subtask doesn't strip code

### ISSUE THREAD

**Issue by djphan** [nuzzio/grunt-strip-code#23]
Hi,

I'm trying out the grunt-strip-code library and I'm running into an issue and I'm running into an odd issue where if I nest my grunt-strip-code config like so:

```
grunt.initConfig({
  strip_code: { 
    js: { /*... my settings */ }
  }
})
```

and run the grunt task (e.g. grunt strip_code:js) it doesn't seem to find my file. But removing the sub task allows me to run grunt-strip-code fine.

When I run the command in verbose mode I get this output:

```
Running "strip_code:js" (strip_code) task
Verifying property strip_code.js exists in config...OK
File: [no files]
Options: testMode=false, intersectionCheck, parityCheck, locale="en_us", patterns=[], blocks=[{"start_block":"/* start-test-block  end-test-block */"}], start_comment=false, end_comment=false, pattern=false, eol=""
```

I know this isn't a file path issue since removing the subtask block shouldn't affect what I define in `your_target` but any thoughts on what could be happening? Let me know if there is more information you need.

**Comment by nuzzio** [comment]
Hi @djphan I am not sure I see what the problem is. The verbose output seems to reflect the default `options`. This is probably since the `options` property is being omitted.
As far as the file being found, you should make sure that the `src` attribute is defined in your file group, for example:

```
js: {
  src: my/file
}
```

If this does not help feel free to post the code for the `strip_code` task and the file location relative to the Gruntfile and perhaps with more information we can find a solution.

**Comment by nuzzio** [comment]
Closing this issue due to lack of response.
